name: Compile PDF Master's Thesis

on:
  push:
    paths:
      - 'Dissertation/**/*' # Si attiva solo se cambia qualcosa in questa cartella

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Download code from repository
        uses: actions/checkout@v4

      - name: Compile Latex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: Dissertation
          compiler: pdflatex # Esegue pdflatex + bibtex in automatico quante volte serve

      - name: Save PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: thesis-pdf
          path: Dissertation/main.pdf
